FROM nginx-rtmp

# NOTE need to clone from github.
# can be changed from jessie to xenial build-pack

VOLUME /etc/nginx

RUN mkdir -p /tmp/http/cryogen
VOLUME /tmp/http/cryogen

RUN mkdir -p /tmp/http/hls
VOLUME /tmp/http/hls

RUN mkdir -p /tmp/http/media
VOLUME /tmp/http/media

USER root

#WORKDIR /tmp/http
#ADD app/resources/public /tmp/http
